name: Examples

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -U https://github.com/Jason2866/platformio-core/archive/refs/tags/v6.1.17.zip
      - name: Shorten path on Windows
        if: matrix.os == 'windows-2022'
        run: |
          powershell -Command "New-Item -ItemType SymbolicLink -Path C:\short -Target $PWD"
          cd C:\short
      - name: Build example
        run: |
          pio run
