name: Examples

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2022]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/Jason2866/platformio-core/archive/refs/tags/v6.1.18.zip
        shell: pwsh
      - name: Shorten path
        run: |
          subst P: $PWD
          cd P:\
        env:
          PLATFORMIO_CORE_DIR: P:\
          PLATFORMIO_PACKAGES_DIR: P:\
          PLATFORMIO_PLATFORMS_DIR: P:\
        shell: pwsh
      - name: Build example
        run: |
          pio run
        env:
          PLATFORMIO_CORE_DIR: P:\
          PLATFORMIO_PACKAGES_DIR: P:\
          PLATFORMIO_PLATFORMS_DIR: P:\
        shell: pwsh
